import { Routes } from '@angular/router';
import { DashboardComponent } from './components/admin/Dashboard/dashboard.component';
import { MembersComponent } from './components/members/members.component';
import { LoginComponent } from './components/auth/login/login.component';
import { MandalComponent } from './components/admin/mandal/mandal.component';
import { SectorComponent } from './components/admin/sector/sector.component';
import { BoothComponent } from './components/admin/booth/booth.component';
import { PannapramukhComponent } from './components/admin/pannapramukh/pannapramukh.component';
import { DesignationComponent } from './components/superadmin/designation/designation.component';
import { SuperDashboardComponent } from './components/superadmin/dashboard/super-dashboard.component';
import { StateComponent } from './components/superadmin/state/state.component';
import { DistrictComponent } from './components/superadmin/district/district.component';
import { VidhanSabhaComponent } from './components/superadmin/vidhansabha/vidhansabha.component';
import { PravasiVoterComponent } from './components/admin/pravasi-voter/pravasi-voter.component';
import { StatePrabhariListComponent } from './components/state-prabhari/list/state-prabhari-list.component';
import { StatePrabhariDashboardComponent } from './components/state-prabhari/dashboard/state-prabhari-dashboard.component';

export const routes: Routes = [
  { path: 'login', component: LoginComponent },
  { path: '', component: DashboardComponent },
  { path: 'members', component: MembersComponent },
  { path: 'mandal', component: MandalComponent },
  { path: 'sector', component: SectorComponent },
  { path: 'booth', component: BoothComponent },
  { path: 'panna-pramukh', component: PannapramukhComponent },
  { path: 'pravasi-voter', component: PravasiVoterComponent },
  { path: 'superadmin/dashboard', component: SuperDashboardComponent },
  { path: 'superadmin/designation', component: DesignationComponent },
  { path: 'superadmin/state', component: StateComponent },
  { path: 'superadmin/state-prabhari', component: StatePrabhariListComponent },
  { path: 'superadmin/district', component: DistrictComponent },
  { path: 'superadmin/vidhansabha', component: VidhanSabhaComponent },
  { path: 'state-prabhari/dashboard', component: StatePrabhariDashboardComponent },
  { path: '**', redirectTo: '' }
];
